# Generated by Django 4.2.6 on 2023-10-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_marca_producto_categori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categori',
            new_name='categoria',
        ),
    ]
